name: Survey CI/CD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Admin module check
        run: ./scripts/admin_module.sh

      - name: Client module check
        run: ./scripts/client_module.sh

      - name: Core module check
        run: ./scripts/core_module.sh