include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics

  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false

  errors:
    close_sinks: error
    missing_required_param: error
    missing_return: error
    # remove line below to enable doc lints
    public_member_api_docs: ignore
    sort_pub_dependencies: ignore
    unawaited_futures: ignore
    sort_constructors_first: ignore
    mixin_inherits_from_not_object: ignore

  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

dart_code_metrics:
  metrics:
    - cyclomatic-complexity: 10
    - maximum-nesting-level: 5
    - source-lines-of-code: 50
  rules:
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-passing-async-when-sync-expected
    - avoid-unnecessary-conditionals
    - avoid-unnecessary-type-assertions
    - avoid-unrelated-type-assertions
    - double-literal-format
    - missing-test-assertion
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-last
    - always-remove-listener
    - avoid-throw-in-catch-block
    - no-magic-number
    - prefer-correct-identifier-length:
        max-identifier-length: 25
        min-identifier-length: 1
    - prefer-match-file-name
    - prefer-moving-to-variable
    - avoid-unnecessary-setstate
    - avoid-expanded-as-spacer

linter:
  rules:
    library_private_types_in_public_api: false