include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics

  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
    enableSuperMixins: true

  errors:
    close_sinks: error
    missing_required_param: error
    missing_return: error
    # remove line below to enable doc lints
    public_member_api_docs: ignore
    sort_pub_dependencies: ignore
    unawaited_futures: ignore
    sort_constructors_first: ignore
    mixin_inherits_from_not_object: ignore

  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    library_private_types_in_public_api: false