arb-dir: lib/src/presentation/localization/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslatedMessages.txt
nullable-getter: false