name: survey_core
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.0.1
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  mockito: ^5.3.2
  very_good_analysis: ^4.0.0

flutter:
  generate: true

  assets:
    - test/assets/test_survey_data.json

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Medium.ttf
    - family: Karla
      fonts:
      - asset: fonts/Karla-Regular.ttf
      - asset: fonts/Karla-Bold.ttf