name: survey_admin
description: Survey SDK

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_colorpicker: ^1.0.3
  flutter_svg: ^2.0.1
  file_picker: ^5.2.5
  get_it: ^7.2.0
  intl: ^0.18.0
  survey_core:
    path: ../core
  universal_html: ^2.2.1

  path_provider: ^2.0.13
dev_dependencies:
  collection: ^1.17.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  test_cov_console: ^0.2.2
  very_good_analysis: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Medium.ttf
    - family: Karla
      fonts:
        - asset: fonts/Karla-Regular.ttf
        - asset: fonts/Karla-Bold.ttf