name: survey_admin
description: Survey SDK

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  flutter_bloc: ^8.0.1

  get_it: ^7.2.0
  equatable: ^2.0.3
  flutter_colorpicker: ^1.0.3
  survey_core:
    path: ../core
  flutter_svg: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
