name: survey_sdk
description: Survey SDK

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.0.1

  get_it: ^7.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  equatable: ^2.0.3
  flutter_form_builder: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
