name: Example CI/CD

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'core/example/**'
  pull_request:
    branches: [ "dev" ]
    paths:
      - 'core/example/**'

defaults:
  run:
    working-directory: ./core/example

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Getting packages
        run: flutter packages get

      - name: Analyzing
        run: flutter analyze
    